def link_fkeys(fkeys):
    for dict in fkeys:
        for key, value in dict.items():
            match key:
                case 'artifact':
                    ...
                case 'schedule':
                    ...
                case 'feature':
                    ...
                case 'historical_event':
                    ...
                case 'circumstance':
                    ...
                case 'historicfigure':
                    ...
                case 'entity_link':
                    ...
                case 'site_link':
                    ...
                case 'hf_link':
                    ...
                case 'entity_former_position_link':
                    ...
                case 'relationship_profile_visual':
                    ...
                case 'intrigue_plot':
                    ...
                case 'intrigue_actor':
                    ...
                case 'entity_position_link':
                    ...
                case 'vague_relationship':
                    ...
                case 'entity_squad_link':
                    ...
                case 'chronicle':
                    ...