version: "3.9"

services:
  db:
    image: postgres:14-alpine

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chroniclespostgres

    volumes:
      - ./data/db:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "3001:3000"

    volumes:
      - /app/frontend/node_modules

    depends_on:
      - backend

  backend:
    build:
      context: ./dfchronicles
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chroniclespostgres
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

    ports:
      - "8002:8000"

    volumes:
      - ./dfchronicles:/app/dfchronicles

    depends_on:
      - db
