# Generated by Django 4.2.4 on 2023-10-04 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('race', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EntityPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('name_male', models.CharField(max_length=100, null=True)),
                ('name_female', models.CharField(max_length=100, null=True)),
                ('spouse', models.CharField(max_length=100, null=True)),
                ('spouse_male', models.CharField(max_length=100, null=True)),
                ('spouse_female', models.CharField(max_length=100, null=True)),
                ('entity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_position', to='chronicle_compiler.entities')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFigures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeared', models.IntegerField(null=True)),
                ('associated_type', models.CharField(max_length=100, null=True)),
                ('birth_year', models.IntegerField(null=True)),
                ('caste', models.CharField(max_length=100, null=True)),
                ('death_year', models.IntegerField(null=True)),
                ('goal', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('race', models.CharField(max_length=100, null=True)),
                ('sphere', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('evilness', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('civ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civ_sites', to='chronicle_compiler.entities')),
                ('cur_owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sites', to='chronicle_compiler.entities')),
            ],
        ),
        migrations.CreateModel(
            name='UndergroundRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('depth', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WrittenContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100, null=True)),
                ('author_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_contents', to='chronicle_compiler.historicalfigures')),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_written_contents', to='chronicle_compiler.writtencontents')),
            ],
        ),
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('name2', models.CharField(max_length=100, null=True)),
                ('inhabitant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inhabitant_structures', to='chronicle_compiler.historicalfigures')),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_structures', to='chronicle_compiler.sites')),
            ],
        ),
        migrations.CreateModel(
            name='SiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=100, null=True)),
                ('civ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civ_site_link', to='chronicle_compiler.entities')),
                ('hf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hf_site_link', to='chronicle_compiler.historicalfigures')),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_link', to='chronicle_compiler.sites')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100, null=True)),
                ('item_subtype', models.CharField(max_length=100, null=True)),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='chronicle_compiler.writtencontents')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipProfileVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fear', models.IntegerField(null=True)),
                ('last_meet_year', models.IntegerField(null=True)),
                ('love', models.IntegerField(null=True)),
                ('loyalty', models.IntegerField(null=True)),
                ('meet_count', models.IntegerField(null=True)),
                ('respect', models.IntegerField(null=True)),
                ('trust', models.IntegerField(null=True)),
                ('source_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_relationship_profile_visual', to='chronicle_compiler.historicalfigures')),
                ('target_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_relationship_profile_visual', to='chronicle_compiler.historicalfigures')),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=100)),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occasion', to='chronicle_compiler.sites')),
            ],
        ),
        migrations.CreateModel(
            name='IntrigueActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, null=True)),
                ('strategy', models.CharField(max_length=100, null=True)),
                ('source_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_intrigue_actor', to='chronicle_compiler.historicalfigures')),
                ('target_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_intrigue_actor', to='chronicle_compiler.historicalfigures')),
            ],
        ),
        migrations.CreateModel(
            name='Identities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField(null=True)),
                ('race', models.CharField(max_length=100, null=True)),
                ('caste', models.CharField(max_length=100, null=True)),
                ('profession', models.CharField(max_length=100, null=True)),
                ('civ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civ_identities', to='chronicle_compiler.entities')),
                ('hf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identities', to='chronicle_compiler.historicalfigures')),
                ('nemesis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nemesis_identities', to='chronicle_compiler.historicalfigures')),
            ],
        ),
        migrations.AddField(
            model_name='historicalfigures',
            name='used_identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_identity_historical_figures', to='chronicle_compiler.identities'),
        ),
        migrations.CreateModel(
            name='HistoricalEvents',
            fields=[
                ('feature_layer_id', models.IntegerField(null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('link_type', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('subregion_id', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('appointer_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointer_hf_historical_events', to='chronicle_compiler.historicalfigures')),
                ('civ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civ_historical_events', to='chronicle_compiler.entities')),
                ('hf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hf_historical_events', to='chronicle_compiler.historicalfigures')),
                ('promise_to_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promise_hf_historical_events', to='chronicle_compiler.historicalfigures')),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_historical_events', to='chronicle_compiler.sites')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEventRelationships',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('relationship', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('source_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_hf_historical_event_relationships', to='chronicle_compiler.historicalfigures')),
                ('target_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_hf_historical_event_relationships', to='chronicle_compiler.historicalfigures')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEventCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacking_squad_deaths', models.IntegerField(null=True)),
                ('attacking_squad_entity_pop', models.IntegerField(null=True)),
                ('attacking_squad_number', models.IntegerField(null=True)),
                ('attacking_squad_race', models.CharField(max_length=100, null=True)),
                ('defending_squad_deaths', models.IntegerField(null=True)),
                ('defending_squad_entity_pop', models.IntegerField(null=True)),
                ('defending_squad_number', models.IntegerField(null=True)),
                ('defending_squad_race', models.CharField(max_length=100, null=True)),
                ('end_year', models.IntegerField(null=True)),
                ('event', models.CharField(max_length=100)),
                ('eventcol', models.IntegerField(null=True)),
                ('feature_layer_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('occasion_id', models.IntegerField(null=True)),
                ('outcome', models.CharField(max_length=100, null=True)),
                ('start_year', models.IntegerField(null=True)),
                ('subregion_id', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('war_eventcol', models.IntegerField(null=True)),
                ('aggressor_entity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_historical_event_collections', to='chronicle_compiler.entities')),
                ('attacking_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_hf_historical_event_collections', to='chronicle_compiler.historicalfigures')),
                ('attacking_squad_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_squad_site_historical_event_collections', to='chronicle_compiler.sites')),
                ('civ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_event_collections', to='chronicle_compiler.entities')),
                ('defender_entity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defend_historical_event_collections', to='chronicle_compiler.entities')),
                ('defending_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defend_hf_historical_event_collections', to='chronicle_compiler.historicalfigures')),
                ('defending_squad_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defend_squad_site_historical_event_collections', to='chronicle_compiler.sites')),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_historical_event_collections', to='chronicle_compiler.sites')),
            ],
        ),
        migrations.CreateModel(
            name='HfSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, null=True)),
                ('total_ip', models.IntegerField(null=True)),
                ('hf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hf_skill', to='chronicle_compiler.historicalfigures')),
            ],
        ),
        migrations.CreateModel(
            name='HfLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=100, null=True)),
                ('link_strength', models.IntegerField(null=True)),
                ('hf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hf_link_target', to='chronicle_compiler.historicalfigures')),
                ('hf_origin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hf_link', to='chronicle_compiler.historicalfigures')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature', to='chronicle_compiler.writtencontents')),
            ],
        ),
        migrations.CreateModel(
            name='EntityPositionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_figure_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hf_entity_position_assignment', to='chronicle_compiler.historicalfigures')),
                ('position_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_position_assignment', to='chronicle_compiler.entityposition')),
            ],
        ),
        migrations.CreateModel(
            name='EntityPopulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('civ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_populations', to='chronicle_compiler.entities')),
            ],
        ),
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=100, null=True)),
                ('civ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_link', to='chronicle_compiler.entities')),
                ('hf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_link', to='chronicle_compiler.historicalfigures')),
            ],
        ),
        migrations.CreateModel(
            name='EntityFormerPositionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(null=True)),
                ('start_year', models.IntegerField(null=True)),
                ('civ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civ_entity_former_position_link', to='chronicle_compiler.entities')),
                ('hf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hf_entity_former_position_link', to='chronicle_compiler.historicalfigures')),
                ('position_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_former_position_link', to='chronicle_compiler.entityposition')),
            ],
        ),
        migrations.AddField(
            model_name='entities',
            name='hf_id',
            field=models.ManyToManyField(related_name='entities', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('site_id', models.IntegerField()),
                ('name_string', models.CharField(max_length=100)),
                ('page_number', models.IntegerField(null=True)),
                ('item_type', models.CharField(max_length=100)),
                ('writing', models.IntegerField(null=True)),
                ('material', models.CharField(max_length=100)),
                ('item_subtype', models.CharField(max_length=100, null=True)),
                ('item_description', models.CharField(max_length=100, null=True)),
                ('holder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hf_artifacts', to='chronicle_compiler.historicalfigures')),
                ('written_content_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_artifacts', to='chronicle_compiler.writtencontents')),
            ],
        ),
    ]
