# Generated by Django 4.2.4 on 2023-10-04 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='entitylink',
            name='civ_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civ_entity_link', to='chronicle_compiler.entities'),
        ),
        migrations.AlterField(
            model_name='entitylink',
            name='hf_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hf_entity_link', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_artifacts', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='entities',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_entities', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='entityformerpositionlink',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_entity_former_position_link', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='entitylink',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_entity_link', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='entitypopulations',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_entity_populations', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='entityposition',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_entity_position', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='entitypositionassignment',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_entity_position_assignment', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='feature',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_feature', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='hflink',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_hf_link', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='hfskill',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_hf_skill', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='historicaleras',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_historical_eras', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='historicaleventcollections',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_historical_event_collections', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='historicaleventrelationships',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_historical_event_relationships', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_historical_events', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='historicalfigures',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_historical_figures', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='identities',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_identities', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='intrigueactor',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_intrigue_actor', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='occasion',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_occasion', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='regions',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_regions', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='relationshipprofilevisual',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_relationship_profile_visual', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_schedule', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='sitelink',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_site_link', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='sites',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_sites', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='structures',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_structures', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='undergroundregions',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_underground_regions', to='chronicle_compiler.world'),
        ),
        migrations.AddField(
            model_name='writtencontents',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_written_contents', to='chronicle_compiler.world'),
        ),
    ]
