# Generated by Django 4.2.4 on 2023-10-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
