# Generated by Django 4.2.4 on 2023-10-04 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chronicle_compiler', '0002_world_alter_entitylink_civ_id_alter_entitylink_hf_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worlds', to=settings.AUTH_USER_MODEL),
        ),
    ]
