# Generated by Django 4.2.4 on 2023-10-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0002_alter_artifact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
