# Generated by Django 4.2.4 on 2023-10-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0003_alter_artifact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='site_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_artifacts', to='chronicle_compiler.sites'),
        ),
    ]
