# Generated by Django 4.2.4 on 2023-10-05 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0003_world_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='body_part',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='caste',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='death_cause',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='injury_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='new_job',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='old_job',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='part_lost',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='race',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Circumstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('hist_event_collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hist_event_collection_circumstance', to='chronicle_compiler.historicaleventcollections')),
                ('hist_event_id', models.ManyToManyField(null=True, related_name='hist_event_circumstance', to='chronicle_compiler.historicalevents')),
                ('world', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_circumstance', to='chronicle_compiler.world')),
            ],
        ),
    ]
