# Generated by Django 4.2.4 on 2023-10-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0004_alter_artifact_site_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='name_string',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
