# Generated by Django 4.2.4 on 2023-10-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0004_historicalevents_body_part_historicalevents_caste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circumstance',
            name='hist_event_id',
            field=models.ManyToManyField(related_name='hist_event_circumstance', to='chronicle_compiler.historicalevents'),
        ),
    ]
