# Generated by Django 4.2.4 on 2023-10-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0005_remove_artifact_name_string_alter_artifact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='item_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='material',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
