# Generated by Django 4.2.4 on 2023-10-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0006_alter_artifact_item_type_alter_artifact_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='writing',
        ),
    ]
