# Generated by Django 4.2.4 on 2023-10-06 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0007_remove_artifact_writing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityposition',
            name='position_id',
        ),
    ]
