# Generated by Django 4.2.4 on 2023-10-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0008_remove_entityposition_position_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitypositionassignment',
            old_name='historical_figure_id',
            new_name='hf_id',
        ),
    ]
