# Generated by Django 4.2.4 on 2023-10-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0009_rename_historical_figure_id_entitypositionassignment_hf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='item_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='item_subtype',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='item_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='material',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='name2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='circumstance',
            name='type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entities',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entities',
            name='race',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entities',
            name='type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entitylink',
            name='link_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entitypopulations',
            name='race',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entityposition',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entityposition',
            name='name_female',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entityposition',
            name='name_male',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entityposition',
            name='spouse',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entityposition',
            name='spouse_female',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entityposition',
            name='spouse_male',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='hflink',
            name='link_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hfskill',
            name='skill',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicaleras',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='historicaleventcollections',
            name='attacking_squad_race',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicaleventcollections',
            name='defending_squad_race',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicaleventcollections',
            name='event',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='historicaleventcollections',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicaleventcollections',
            name='outcome',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicaleventcollections',
            name='type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='caste',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='death_cause',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='injury_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='link_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='new_job',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='old_job',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='position',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='race',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='reason',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='relationship',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='state',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfigures',
            name='associated_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfigures',
            name='caste',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfigures',
            name='goal',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfigures',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfigures',
            name='race',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfigures',
            name='sphere',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='identities',
            name='caste',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='identities',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='identities',
            name='profession',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='identities',
            name='race',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='intrigueactor',
            name='role',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='intrigueactor',
            name='strategy',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='intrigueplot',
            name='type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='regions',
            name='evilness',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='regions',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='regions',
            name='type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='item_subtype',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='item_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sitelink',
            name='link_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sites',
            name='type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='structures',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='structures',
            name='name2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='structures',
            name='type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='undergroundregions',
            name='type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='world',
            name='name2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='writtencontents',
            name='form',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='writtencontents',
            name='style',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='writtencontents',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
