# Generated by Django 4.2.4 on 2023-10-06 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0010_alter_artifact_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='structure_local_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_artifacts', to='chronicle_compiler.structures'),
        ),
    ]
