# Generated by Django 4.2.4 on 2023-10-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0013_historicalfigures_deity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitypositionassignment',
            name='squad_id',
            field=models.IntegerField(null=True),
        ),
    ]
