# Generated by Django 4.2.4 on 2023-10-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0014_entitypositionassignment_squad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occasion',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='occasion',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='occasion',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='occasion',
            name='type',
        ),
    ]
