# Generated by Django 4.2.4 on 2023-10-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0015_remove_occasion_end_year_remove_occasion_site_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaleventcollections',
            name='attacking_squad_entity_pop',
        ),
        migrations.RemoveField(
            model_name='historicaleventcollections',
            name='defending_squad_entity_pop',
        ),
        migrations.AddField(
            model_name='historicaleventcollections',
            name='attacking_squad_animated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaleventcollections',
            name='coords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicaleventcollections',
            name='defending_squad_animated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaleventcollections',
            name='noncom_hfid',
            field=models.ManyToManyField(null=True, related_name='noncom_hf_historical_event_collections', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.RemoveField(
            model_name='historicaleventcollections',
            name='attacking_hfid',
        ),
        migrations.RemoveField(
            model_name='historicaleventcollections',
            name='defending_hfid',
        ),
        migrations.RemoveField(
            model_name='historicaleventcollections',
            name='event',
        ),
        migrations.AlterField(
            model_name='historicalfigures',
            name='deity',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaleventcollections',
            name='attacking_hfid',
            field=models.ManyToManyField(null=True, related_name='attack_hf_historical_event_collections', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicaleventcollections',
            name='defending_hfid',
            field=models.ManyToManyField(null=True, related_name='defend_hf_historical_event_collections', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicaleventcollections',
            name='event',
            field=models.ManyToManyField(related_name='event_historical_event_collections', to='chronicle_compiler.historicalevents'),
        ),
    ]
