# Generated by Django 4.2.4 on 2023-10-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0017_alter_entitypopulations_population_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaleventcollections',
            name='attacking_hfid',
            field=models.ManyToManyField(related_name='attack_hf_historical_event_collections', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AlterField(
            model_name='historicaleventcollections',
            name='defending_hfid',
            field=models.ManyToManyField(related_name='defend_hf_historical_event_collections', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AlterField(
            model_name='historicaleventcollections',
            name='noncom_hfid',
            field=models.ManyToManyField(related_name='noncom_hf_historical_event_collections', to='chronicle_compiler.historicalfigures'),
        ),
    ]
