# Generated by Django 4.2.4 on 2023-10-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0018_alter_historicaleventcollections_attacking_hfid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaleventcollections',
            name='eventcol',
        ),
        migrations.RemoveField(
            model_name='historicaleventcollections',
            name='feature_layer_id',
        ),
        migrations.RemoveField(
            model_name='historicaleventcollections',
            name='war_eventcol',
        ),
        migrations.AlterField(
            model_name='historicaleventcollections',
            name='attacking_squad_race',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicaleventcollections',
            name='defending_squad_race',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
