# Generated by Django 4.2.4 on 2023-10-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0020_historicaleventcollections_target_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfigures',
            name='journey_pet',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='historicalfigures',
            name='used_identity',
        ),
        migrations.AddField(
            model_name='historicalfigures',
            name='used_identity',
            field=models.ManyToManyField(related_name='used_identity_historical_figures', to='chronicle_compiler.identities'),
        ),
    ]
