# Generated by Django 4.2.4 on 2023-10-07 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0021_historicalfigures_journey_pet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfigures',
            name='ent_pop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ent_pop_historical_figures', to='chronicle_compiler.entitypopulations'),
        ),
    ]
