# Generated by Django 4.2.4 on 2023-10-07 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0022_historicalfigures_ent_pop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfigures',
            name='current_identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_identity_historical_figures', to='chronicle_compiler.identities'),
        ),
    ]
