# Generated by Django 4.2.4 on 2023-10-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0023_historicalfigures_current_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfigures',
            name='force',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalfigures',
            name='held_artifact',
            field=models.ManyToManyField(related_name='holds_artifact_historical_figures', to='chronicle_compiler.artifact'),
        ),
    ]
