# Generated by Django 4.2.4 on 2023-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0024_historicalfigures_force_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfigures',
            name='animated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalfigures',
            name='animated_string',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
