# Generated by Django 4.2.4 on 2023-10-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0025_historicalfigures_animated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelink',
            name='structure_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_link', to='chronicle_compiler.structures'),
        ),
    ]
