# Generated by Django 4.2.4 on 2023-10-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0026_sitelink_structure_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitylink',
            name='link_strength',
            field=models.IntegerField(null=True),
        ),
    ]
