# Generated by Django 4.2.4 on 2023-10-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0027_entitylink_link_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshipprofilevisual',
            name='known_identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='known_identity_relationship_profile_visual', to='chronicle_compiler.identities'),
        ),
        migrations.AddField(
            model_name='relationshipprofilevisual',
            name='rep_friendly',
            field=models.IntegerField(null=True),
        ),
    ]
