# Generated by Django 4.2.4 on 2023-10-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0028_relationshipprofilevisual_known_identity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPositionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(null=True)),
                ('hf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hf_entity_position_link', to='chronicle_compiler.historicalfigures')),
                ('position_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_position_link', to='chronicle_compiler.entityposition')),
                ('world', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_entity_position_link', to='chronicle_compiler.world')),
            ],
        ),
    ]
