# Generated by Django 4.2.4 on 2023-10-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0029_entitypositionlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='VagueRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500)),
                ('source_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_vague_relationship', to='chronicle_compiler.historicalfigures')),
                ('target_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_vague_relationship', to='chronicle_compiler.historicalfigures')),
                ('world', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_vague_relationship', to='chronicle_compiler.world')),
            ],
        ),
    ]
