# Generated by Django 4.2.4 on 2023-10-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0030_vaguerelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('type', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_site_property', to='chronicle_compiler.historicalfigures')),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_property', to='chronicle_compiler.sites')),
                ('world', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_site_property', to='chronicle_compiler.world')),
            ],
        ),
        migrations.CreateModel(
            name='EntitySquadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_id', models.IntegerField(null=True)),
                ('squad_position', models.IntegerField(null=True)),
                ('start_year', models.IntegerField(null=True)),
                ('civ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civ_entity_squad_link', to='chronicle_compiler.entities')),
                ('hf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hf_entity_squad_link', to='chronicle_compiler.historicalfigures')),
                ('world', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_entity_squad_link', to='chronicle_compiler.world')),
            ],
        ),
    ]
