# Generated by Django 4.2.4 on 2023-10-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0031_siteproperty_entitysquadlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrigueplot',
            name='civ_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civ_intrigue_plot', to='chronicle_compiler.entities'),
        ),
        migrations.AddField(
            model_name='intrigueplot',
            name='on_hold',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
