# Generated by Django 4.2.4 on 2023-10-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0032_intrigueplot_civ_id_intrigueplot_on_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitypositionlink',
            name='civ_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civ_entity_position_link', to='chronicle_compiler.entities'),
        ),
        migrations.AddField(
            model_name='intrigueactor',
            name='civ_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civ_intrigue_actor', to='chronicle_compiler.entities'),
        ),
        migrations.AddField(
            model_name='intrigueplot',
            name='artifact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_intrigue_plot', to='chronicle_compiler.artifact'),
        ),
    ]
