# Generated by Django 4.2.4 on 2023-10-07 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0034_relationshipprofilevisual_rep_information_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_role', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(max_length=500, null=True)),
                ('actor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_plot_actor', to='chronicle_compiler.historicalfigures')),
                ('delegated_plot_hfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_plot_hfid_plot_actor', to='chronicle_compiler.historicalfigures')),
                ('plot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plot_plot_actor', to='chronicle_compiler.intrigueplot')),
                ('world', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_plot_actor', to='chronicle_compiler.world')),
            ],
        ),
    ]
