# Generated by Django 4.2.4 on 2023-10-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0035_plotactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrigueplot',
            name='delegated_plot_hfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_plot_hfid_intrigue_plot', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='plotactor',
            name='has_messenger',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
