# Generated by Django 4.2.4 on 2023-10-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0036_intrigueplot_delegated_plot_hfid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrigueactor',
            name='promised_actor_immortality',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='intrigueactor',
            name='promised_me_immortality',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
