# Generated by Django 4.2.4 on 2023-10-10 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0037_intrigueactor_promised_actor_immortality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='body_state',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='circumstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circumstance_historical_events', to='chronicle_compiler.historicaleventcollections'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='convicted_hfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convicted_hfid_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='convicter_enid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convicter_enid_historical_events', to='chronicle_compiler.entities'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='coords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='crime',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='death_penalty',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='fooled_hfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fooled_hf_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='framer_hfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framer_hf_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='stash_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stash_site_historical_events', to='chronicle_compiler.sites'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_historical_events', to='chronicle_compiler.structures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='theft_method',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='wrongful_conviction',
            field=models.BooleanField(null=True),
        ),
    ]
