# Generated by Django 4.2.4 on 2023-10-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0038_historicalevents_body_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='coords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='rectangle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='structures',
            name='inhabitant',
        ),
        migrations.AddField(
            model_name='structures',
            name='inhabitant',
            field=models.ManyToManyField(related_name='inhabitant_structures', to='chronicle_compiler.historicalfigures'),
        ),
    ]
