# Generated by Django 4.2.4 on 2023-10-10 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0039_sites_coords_sites_rectangle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='first',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='knowledge',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='structures',
            name='civ_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civ_structures', to='chronicle_compiler.entities'),
        ),
    ]
