# Generated by Django 4.2.4 on 2023-10-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0042_historicalevents_link_historicalevents_position_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='artifact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_historical_events', to='chronicle_compiler.artifact'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='attacker_civ_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacker_civ_historical_events', to='chronicle_compiler.entities'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='attacker_general_hfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacker_general_hfid_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='defender_civ_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defender_civ_historical_events', to='chronicle_compiler.entities'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='defender_general_hfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defender_general_hfid_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_historical_events', to='chronicle_compiler.identities'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='initiating_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiating_entity_historical_events', to='chronicle_compiler.entities'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='joining_entity',
            field=models.ManyToManyField(related_name='joining_entity_historical_events', to='chronicle_compiler.entities'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='occasion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occasion_historical_events', to='chronicle_compiler.occasion'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_historical_events', to='chronicle_compiler.schedule'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='subtype',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='target_enid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_enid_historical_events', to='chronicle_compiler.entities'),
        ),
        migrations.RemoveField(
            model_name='historicalevents',
            name='civ_id',
        ),
        migrations.RemoveField(
            model_name='historicalevents',
            name='site_id',
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='civ_id',
            field=models.ManyToManyField(related_name='civ_historical_events', to='chronicle_compiler.entities'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='site_id',
            field=models.ManyToManyField(related_name='site_historical_events', to='chronicle_compiler.sites'),
        ),
    ]
