# Generated by Django 4.2.4 on 2023-10-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0043_historicalevents_artifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='site_civ_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_civ_id_historical_events', to='chronicle_compiler.entities'),
        ),
    ]
