# Generated by Django 4.2.4 on 2023-10-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0044_historicalevents_site_civ_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='competitor_hfid',
            field=models.ManyToManyField(related_name='competitor_hfid_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='dispute',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='winner_hfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_hfid_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
    ]
