# Generated by Django 4.2.4 on 2023-10-12 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0045_historicalevents_competitor_hfid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='circumstance_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circumstance_historical_events', to='chronicle_compiler.historicaleventcollections'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='detected',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='new_caste',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='new_race',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='old_caste',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='old_race',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='quality',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='returning',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='written_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_content_historical_events', to='chronicle_compiler.writtencontents'),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='circumstance',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
