# Generated by Django 4.2.4 on 2023-10-12 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0046_historicalevents_circumstance_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='identity_rep',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='new_account',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='old_account',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='target_identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_identity_historical_events', to='chronicle_compiler.identities'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='target_identity_rep',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
