# Generated by Django 4.2.4 on 2023-10-12 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0047_historicalevents_identity_rep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='method',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='secret_goal',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='master_world_construction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_world_construction_historical_events', to='chronicle_compiler.worldconstruction'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='world_construction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='world_construction_historical_events', to='chronicle_compiler.worldconstruction'),
        ),
    ]
