# Generated by Django 4.2.4 on 2023-10-12 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0048_worldconstruction_historicalevents_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='corruptor_seen_as',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='inherited',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='last_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_owner_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='mood',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='new_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_leader_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='new_site_civ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_site_civ_historical_events', to='chronicle_compiler.entities'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='purchased_unowned',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='rebuilt_ruined',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='site_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_property_historical_events', to='chronicle_compiler.siteproperty'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='successful',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='target_seen_as',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
