# Generated by Django 4.2.4 on 2023-10-12 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0049_historicalevents_corruptor_seen_as_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='account_shift',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='expelled_hfids',
            field=models.ManyToManyField(related_name='expelled_hfids_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='prison_months',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='shrine_amount_destroyed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='target_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_site_id_historical_events', to='chronicle_compiler.sites'),
        ),
    ]
