# Generated by Django 4.2.4 on 2023-10-12 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0050_historicalevents_account_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='actor_hfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_hfid_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='conspirator_hfid',
            field=models.ManyToManyField(related_name='conspirator_hfid_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='instigator_hfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instigator_hfid_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='position_taker_hfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_taker_hfid_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='resident_civ_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_civ_historical_events', to='chronicle_compiler.entities'),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='feature_layer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_layer_historical_events', to='chronicle_compiler.undergroundregions'),
        ),
    ]
