# Generated by Django 4.2.4 on 2023-10-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0051_historicalevents_actor_hfid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MusicalForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PoeticForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalevents',
            name='promise_to_hfid',
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='held_firm_in_interrogation',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='pets',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='dance_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dance_form_historical_events', to='chronicle_compiler.danceforms'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='musical_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musical_form_historical_events', to='chronicle_compiler.musicalforms'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='poetic_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poetic_form_historical_events', to='chronicle_compiler.poeticforms'),
        ),
    ]
