# Generated by Django 4.2.4 on 2023-10-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0052_danceforms_musicalforms_poeticforms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='abuse_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='bodies',
            field=models.ManyToManyField(related_name='bodies_historical_events', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='mat',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
