# Generated by Django 4.2.4 on 2023-10-14 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0053_historicalevents_abuse_type_historicalevents_bodies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circumstance',
            name='hist_event_id',
        ),
        migrations.RemoveField(
            model_name='historicalevents',
            name='circumstance_collection',
        ),
        migrations.AddField(
            model_name='worldconstruction',
            name='chronicle_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldconstruction',
            name='coords',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='worldconstruction',
            name='type',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldconstruction',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world_world_construction', to='chronicle_compiler.world'),
        ),
    ]
