# Generated by Django 4.2.4 on 2023-10-15 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0055_danceforms_chronicle_id_danceforms_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='coords',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='regions',
            name='force',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='force_regions', to='chronicle_compiler.historicalfigures'),
        ),
        migrations.AddField(
            model_name='undergroundregions',
            name='coords',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='worldconstruction',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
