# Generated by Django 4.2.4 on 2023-10-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0057_writtencontentreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceforms',
            name='description',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='musicalforms',
            name='description',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='poeticforms',
            name='description',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='writtencontents',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
