# Generated by Django 4.2.4 on 2023-10-18 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0059_remove_feature_reference_remove_schedule_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writtencontentreference',
            name='written_content_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_written_content_reference', to='chronicle_compiler.writtencontents'),
        ),
        migrations.AlterField(
            model_name='writtencontentreference',
            name='written_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_written_content_reference', to='chronicle_compiler.writtencontents'),
        ),
    ]
