# Generated by Django 4.2.4 on 2023-10-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0060_writtencontentreference_written_content_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaleventcollections',
            name='event_collection',
            field=models.ManyToManyField(related_name='event_historical_event_collections', to='chronicle_compiler.historicaleventcollections'),
        ),
        migrations.AddField(
            model_name='historicaleventcollections',
            name='parent_event_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_event_collection_historical_event_collections', to='chronicle_compiler.historicaleventcollections'),
        ),
        migrations.AddField(
            model_name='historicaleventcollections',
            name='war_event_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='war_event_collection_historical_event_collections', to='chronicle_compiler.historicaleventcollections'),
        ),
    ]
