# Generated by Django 4.2.4 on 2023-11-03 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chronicle_compiler', '0061_historicaleventcollections_event_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField()),
                ('prompt', models.CharField()),
                ('response', models.CharField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
