# Generated by Django 4.2.4 on 2023-11-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0062_generations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generations',
            name='object',
        ),
    ]
