# Generated by Django 4.2.4 on 2023-11-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0063_remove_generations_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='generations',
            name='object',
            field=models.CharField(default='Undefined'),
            preserve_default=False,
        ),
    ]
