# Generated by Django 4.2.4 on 2023-11-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0064_generations_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaleventcollections',
            old_name='attacking_squad_animated',
            new_name='attacking_squad_is_undead',
        ),
        migrations.RenameField(
            model_name='historicaleventcollections',
            old_name='defending_squad_animated',
            new_name='defending_squad_is_undead',
        ),
    ]
