# Generated by Django 4.2.4 on 2023-11-07 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0065_rename_attacking_squad_animated_historicaleventcollections_attacking_squad_is_undead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generations',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
