# Generated by Django 4.2.4 on 2023-11-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0066_generations_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalevents',
            old_name='hf_id',
            new_name='perpetrator_hfid',
        ),
    ]
