# Generated by Django 4.2.4 on 2023-11-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0070_rename_generations_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='title',
            field=models.CharField(default='No Generated Title'),
            preserve_default=False,
        ),
    ]
