# Generated by Django 4.2.4 on 2023-11-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle_compiler', '0071_generation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='score',
        ),
    ]
